[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
